# Generated by Django 2.2.1 on 2019-06-01 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('driverType', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='准驾类型')),
                ('desc', models.CharField(max_length=20, verbose_name='描述')),
            ],
            options={
                'verbose_name': '准驾类型',
            },
        ),
        migrations.CreateModel(
            name='CheckMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkMan', models.CharField(max_length=120, unique=True, verbose_name='查处人')),
            ],
            options={
                'verbose_name': '检查人',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverName', models.CharField(max_length=15, verbose_name='司机姓名')),
                ('telPhone', models.CharField(blank=True, max_length=20, null=True, verbose_name='司机电话')),
                ('idCardNO', models.CharField(max_length=20, verbose_name='身份证号码')),
                ('truckNO', models.CharField(blank=True, max_length=20, null=True, verbose_name='驾驶车辆')),
                ('firstCardDate', models.DateField(blank=True, null=True, verbose_name='初次发证日期')),
                ('illegalCount', models.IntegerField(blank=True, null=True, verbose_name='违章次数')),
                ('isDelete', models.BooleanField(default=False, editable=False)),
                ('driverType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='securitye.CarModel', verbose_name='准驾类型')),
            ],
            options={
                'verbose_name': '1.司机信息',
            },
        ),
        migrations.CreateModel(
            name='DriverCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=30, verbose_name='车队名称')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否有效')),
                ('recordMan', models.CharField(blank=True, max_length=15, null=True, verbose_name='记录人')),
                ('recordTime', models.DateField(auto_now_add=True, null=True, verbose_name='记录时间')),
                ('cancelMan', models.CharField(blank=True, max_length=15, null=True, verbose_name='更新人')),
                ('cancelTime', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '车队',
            },
        ),
        migrations.CreateModel(
            name='Illegal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illegalDate', models.DateField(verbose_name='违章日期')),
                ('illegalAttribute', models.CharField(max_length=15, verbose_name='违章性质')),
                ('illegalCode', models.CharField(max_length=15, verbose_name='违章代码')),
                ('illegalDesc', models.TextField(verbose_name='三违行为概述')),
                ('illegalMan', models.CharField(max_length=120, verbose_name='违章者')),
                ('resDept', models.CharField(max_length=120, verbose_name='责任部门(或公司)')),
                ('resGroup', models.CharField(max_length=120, verbose_name='班组')),
                ('handle', models.CharField(max_length=20, verbose_name='处理情况')),
                ('resMoney', models.FloatField(verbose_name='罚金(元')),
                ('allRes', models.TextField(verbose_name='连带责任')),
                ('checkMan', models.CharField(max_length=120, verbose_name='查处人')),
                ('bakMsg', models.TextField(verbose_name='备 注')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '人员违章',
            },
        ),
        migrations.CreateModel(
            name='IllegalAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illegalAttribute', models.CharField(max_length=15, unique=True, verbose_name='违章性质')),
            ],
            options={
                'verbose_name': '违章性质',
            },
        ),
        migrations.CreateModel(
            name='OutCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truckNO', models.CharField(max_length=15, verbose_name='车牌号')),
                ('driverName', models.CharField(max_length=15, verbose_name='驾驶者姓名')),
                ('sex', models.CharField(max_length=2, verbose_name='性别')),
                ('cardID', models.CharField(max_length=20, verbose_name='身份证号码')),
                ('telPhone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('inPortNO', models.CharField(max_length=20, verbose_name='进港证编号')),
                ('unitName', models.CharField(max_length=45, verbose_name='单 位')),
                ('position', models.CharField(max_length=15, verbose_name='职务')),
                ('lxr', models.CharField(max_length=15, verbose_name='单位联系人')),
                ('unitPhone', models.CharField(max_length=20, verbose_name='单位联系人电话')),
                ('inResion', models.TextField(verbose_name='进港理由')),
                ('trainStatus', models.CharField(max_length=20, verbose_name='培训情况')),
                ('firstCardDate', models.DateField(verbose_name='初次发证时间')),
                ('vaildStartDate', models.DateField(verbose_name='有效期')),
                ('vaildEndDate', models.DateField(verbose_name='有效期')),
                ('illegalCount', models.IntegerField(default=0, verbose_name='违章次数')),
                ('bakMsg', models.TextField(verbose_name='备注')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '外来车辆',
            },
        ),
        migrations.CreateModel(
            name='OutMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=15, verbose_name='姓 名')),
                ('sex', models.CharField(max_length=2, verbose_name='性别')),
                ('cardID', models.CharField(max_length=20, verbose_name='身份证号码')),
                ('telPhone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('inPortNO', models.CharField(max_length=20, verbose_name='进港证编号')),
                ('unitName', models.CharField(max_length=45, verbose_name='单 位')),
                ('position', models.CharField(max_length=15, verbose_name='职务')),
                ('lxr', models.CharField(max_length=15, verbose_name='单位联系人')),
                ('unitPhone', models.CharField(max_length=20, verbose_name='单位联系人电话')),
                ('certificateDate', models.DateField(verbose_name='初次发证时间')),
                ('vaildStartDate', models.DateField(verbose_name='有效期')),
                ('vaildEndDate', models.DateField(verbose_name='有效期')),
                ('illegalCount', models.IntegerField(default=0, verbose_name='违章次数')),
                ('bakMsg', models.TextField(max_length=100, verbose_name='备注')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '外来人员',
            },
        ),
        migrations.CreateModel(
            name='ResDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resDept', models.CharField(max_length=120, unique=True, verbose_name='责任部门(或公司)')),
            ],
            options={
                'verbose_name': '责任部门(或公司)',
            },
        ),
        migrations.CreateModel(
            name='ResGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resGroup', models.CharField(max_length=120, unique=True, verbose_name='班组')),
            ],
            options={
                'verbose_name': '责任班组',
            },
        ),
        migrations.CreateModel(
            name='OutManCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateField(verbose_name='开始有效期')),
                ('endTime', models.DateField(verbose_name='结束有效期')),
                ('recordMan', models.CharField(max_length=15, verbose_name='记录人')),
                ('recordTime', models.DateField(auto_now_add=True, verbose_name='记录时间')),
                ('cancelMan', models.CharField(max_length=15, verbose_name='取消人')),
                ('cancelTime', models.DateTimeField(verbose_name='取消时间')),
                ('isOn', models.CharField(default='Y', max_length=1, verbose_name='是否有效')),
                ('isDelete', models.BooleanField(default=False)),
                ('manID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securitye.OutMan')),
            ],
            options={
                'verbose_name': '外来人员进港证有效期',
            },
        ),
        migrations.CreateModel(
            name='OutCarTran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(verbose_name='培训情况')),
                ('recordMan', models.CharField(max_length=20, verbose_name='记录人')),
                ('recordTime', models.DateField(auto_now_add=True, verbose_name='记录时间')),
                ('cancelMan', models.CharField(max_length=20, verbose_name='取消人')),
                ('cancelTime', models.DateField(verbose_name='取消时间')),
                ('isOn', models.CharField(default='Y', max_length=1, verbose_name='是否有效')),
                ('isDelete', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securitye.OutCar')),
            ],
            options={
                'verbose_name': '外车培训',
            },
        ),
        migrations.CreateModel(
            name='OutCarCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateField(verbose_name='开始有效期')),
                ('endTime', models.DateField(verbose_name='结束有效期')),
                ('recordMan', models.CharField(max_length=15, verbose_name='记录人')),
                ('recordTime', models.DateField(auto_now_add=True, verbose_name='记录时间')),
                ('cancelMan', models.CharField(max_length=15, verbose_name='取消人')),
                ('cancelTime', models.DateTimeField(verbose_name='取消时间')),
                ('isOn', models.CharField(default='Y', max_length=1, verbose_name='是否有效')),
                ('isDelete', models.BooleanField(default=False)),
                ('carID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securitye.OutCar')),
            ],
            options={
                'verbose_name': '外车进港证有效期',
            },
        ),
        migrations.CreateModel(
            name='IllegalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('cTime', models.DateField(auto_now_add=True, verbose_name='图片日期')),
                ('isDelete', models.BooleanField(default=False)),
                ('illegal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securitye.Illegal', verbose_name='IllegalID')),
            ],
            options={
                'verbose_name': '人员违章图片',
            },
        ),
        migrations.CreateModel(
            name='DriverTran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(verbose_name='培训情况')),
                ('recordMan', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='记录人')),
                ('recordTime', models.DateField(auto_now_add=True, verbose_name='记录时间')),
                ('cancelMan', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='取消人')),
                ('cancelTime', models.DateField(blank=True, editable=False, null=True, verbose_name='取消时间')),
                ('isDelete', models.BooleanField(blank=True, default=False, editable=False, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securitye.Driver')),
            ],
            options={
                'verbose_name': '司机培训',
            },
        ),
        migrations.CreateModel(
            name='DriverTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testScore', models.FloatField(verbose_name='考试成绩')),
                ('testDate', models.DateTimeField(verbose_name='考试时间')),
                ('recordMan', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='记录人')),
                ('recordTime', models.DateField(auto_now_add=True, verbose_name='记录时间')),
                ('cancelMan', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='取消人')),
                ('cancelTime', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='取消时间')),
                ('isDelete', models.BooleanField(blank=True, default=False, editable=False, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securitye.Driver')),
            ],
            options={
                'verbose_name': '司机考试',
            },
        ),
        migrations.CreateModel(
            name='DriverTempInCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateField(verbose_name='开始有效期')),
                ('endTime', models.DateField(verbose_name='结束有效期')),
                ('recordMan', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='记录人')),
                ('recordTime', models.DateField(auto_now_add=True, verbose_name='记录时间')),
                ('cancelMan', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='取消人')),
                ('cancelTime', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='取消时间')),
                ('isDelete', models.BooleanField(default=False, editable=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securitye.Driver')),
            ],
            options={
                'verbose_name': '临时进港证',
            },
        ),
        migrations.CreateModel(
            name='DriverLongInCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateField(verbose_name='开始有效期')),
                ('endTime', models.DateField(verbose_name='结束有效期')),
                ('recordMan', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='记录人')),
                ('recordTime', models.DateField(auto_now_add=True, verbose_name='记录时间')),
                ('cancelMan', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='取消人')),
                ('cancelTime', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='取消时间')),
                ('isDelete', models.BooleanField(default=False, editable=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securitye.Driver')),
            ],
            options={
                'verbose_name': '长期进港证',
            },
        ),
        migrations.CreateModel(
            name='DriverLearnCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateField(verbose_name='开始有效期')),
                ('endTime', models.DateField(verbose_name='结束有效期')),
                ('recordMan', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='记录人')),
                ('recordTime', models.DateField(auto_now_add=True, verbose_name='记录时间')),
                ('cancelMan', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='取消人')),
                ('cancelTime', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='取消时间')),
                ('isDelete', models.BooleanField(default=False, editable=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securitye.Driver')),
            ],
            options={
                'verbose_name': '司机学习证',
            },
        ),
        migrations.CreateModel(
            name='DriverJobCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateField(verbose_name='开始有效期')),
                ('endTime', models.DateField(verbose_name='结束有效期')),
                ('recordMan', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='记录人')),
                ('recordTime', models.DateField(auto_now_add=True, null=True, verbose_name='记录时间')),
                ('cancelMan', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='取消人')),
                ('cancelTime', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='取消时间')),
                ('isDelete', models.BooleanField(default=False, editable=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securitye.Driver')),
            ],
            options={
                'verbose_name': '1.1.司机从业资格证',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='truckCompanyCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='securitye.DriverCompany', verbose_name='车队'),
        ),
    ]
