# Generated by Django 2.2.1 on 2019-06-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securitye', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': '0.1 准驾类型'},
        ),
        migrations.AlterModelOptions(
            name='checkman',
            options={'verbose_name': '4.4 检查人'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': '1.0 司机信息'},
        ),
        migrations.AlterModelOptions(
            name='drivercompany',
            options={'verbose_name': '0.0 车队'},
        ),
        migrations.AlterModelOptions(
            name='driverjobcard',
            options={'verbose_name': '1.1 司机从业资格证'},
        ),
        migrations.AlterModelOptions(
            name='driverlearncard',
            options={'verbose_name': '1.4 司机学习证'},
        ),
        migrations.AlterModelOptions(
            name='driverlongincard',
            options={'verbose_name': '1.6 长期进港证'},
        ),
        migrations.AlterModelOptions(
            name='drivertempincard',
            options={'verbose_name': '1.5 临时进港证'},
        ),
        migrations.AlterModelOptions(
            name='drivertest',
            options={'verbose_name': '1.3 司机考试'},
        ),
        migrations.AlterModelOptions(
            name='drivertran',
            options={'verbose_name': '1.2 司机培训'},
        ),
        migrations.AlterModelOptions(
            name='illegal',
            options={'verbose_name': '4.0 人员违章'},
        ),
        migrations.AlterModelOptions(
            name='illegalattribute',
            options={'verbose_name': '4.1 违章性质'},
        ),
        migrations.AlterModelOptions(
            name='illegalimage',
            options={'verbose_name': '4.1 人员违章图片'},
        ),
        migrations.AlterModelOptions(
            name='outcar',
            options={'verbose_name': '3.0 外来车辆'},
        ),
        migrations.AlterModelOptions(
            name='outcarcard',
            options={'verbose_name': '3.2 外车进港证有效期'},
        ),
        migrations.AlterModelOptions(
            name='outcartran',
            options={'verbose_name': '3.1 外车培训'},
        ),
        migrations.AlterModelOptions(
            name='outman',
            options={'verbose_name': '2.0 外来人员'},
        ),
        migrations.AlterModelOptions(
            name='outmancard',
            options={'verbose_name': '2.1 外来人员进港证有效期'},
        ),
        migrations.AlterModelOptions(
            name='resdept',
            options={'verbose_name': '4.2 责任部门(或公司)'},
        ),
        migrations.AlterModelOptions(
            name='resgroup',
            options={'verbose_name': '4.3 责任班组'},
        ),
        migrations.AddField(
            model_name='driver',
            name='cancelMan',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='取消人'),
        ),
        migrations.AddField(
            model_name='driver',
            name='cancelTime',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='取消时间'),
        ),
        migrations.AddField(
            model_name='driver',
            name='recordMan',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='记录人'),
        ),
        migrations.AddField(
            model_name='driver',
            name='recordTime',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='记录时间'),
        ),
    ]
