# Generated by Django 2.1.7 on 2019-06-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securitye', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='recordMan',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='record',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='record',
        ),
        migrations.RemoveField(
            model_name='drivercompany',
            name='record',
        ),
        migrations.RemoveField(
            model_name='driverjobcard',
            name='record',
        ),
        migrations.RemoveField(
            model_name='driverlearncard',
            name='record',
        ),
        migrations.RemoveField(
            model_name='driverlongincard',
            name='record',
        ),
        migrations.RemoveField(
            model_name='drivertempincard',
            name='record',
        ),
        migrations.RemoveField(
            model_name='drivertest',
            name='record',
        ),
        migrations.RemoveField(
            model_name='drivertran',
            name='record',
        ),
        migrations.RemoveField(
            model_name='illegal',
            name='record',
        ),
        migrations.RemoveField(
            model_name='outcar',
            name='record',
        ),
        migrations.RemoveField(
            model_name='outcarcard',
            name='record',
        ),
        migrations.RemoveField(
            model_name='outcartran',
            name='record',
        ),
        migrations.RemoveField(
            model_name='outman',
            name='record',
        ),
        migrations.RemoveField(
            model_name='outmancard',
            name='record',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
