# Generated by Django 2.2.1 on 2019-06-01 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securitye', '0002_auto_20190601_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertran',
            name='tranDate',
            field=models.DateField(default=datetime.datetime(2019, 6, 1, 20, 20, 57, 515885), verbose_name='培训时间'),
        ),
    ]
