# Generated by Django 2.1.7 on 2019-06-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securitye', '0002_auto_20190603_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='isDelete',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
