# Generated by Django 2.2.1 on 2019-06-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securitye', '0003_drivertran_trandate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivertran',
            name='tranDate',
            field=models.DateField(default=None, verbose_name='培训时间'),
        ),
    ]
